# Scripts {#scripts-chapter}
Ok, let's take a break before all the theoretical chapters to discuss about scripts. 
<br>
I always say this word when talking to you about my job, but what are they? A script is essentially an ordered list of commands, used to not have to write again and again the same commands on the console. It can contain everything you type in the console, like functions, operations and even comments; in this way, you can do an analysis and store it as a "text" file that you can use as reference (so you know what you have done), use for another analysis, edit, share with others...
<br>
You will <strong>always</strong> write code in scripts, for all these reasons.
<br>
<br>
Let's see how to create a script, write some code in it and run part of the script or even a small part of it in RStudio.

<div style="text-align:center">
<video height=500px width=auto controls>
  <source src="video/create-script.mov">
</video>
</div>

<p class="plist">In the video we see a series of actions:</p>
<ol>
  <li>To create a script, click the button on top left, then select "R Script" (or File -> New File -> R Script)</li>
  <li>Start writing the commands (even comments)</li>
  <li>To run a single line click "Run"</li>
  <li>To run the whole script (R starts from the beginning) click "Source")</li>
</ol>

<strong>Suggetion</strong>: Comment, comment, comment everything. I know it is time consuming, but you will be so happy and greatful to read comments that help you understand what you've done months (or weeks) before.
<br>


## Save {-}
To save a script "File -> Save" or the usual shortcut "Ctrl-S" (Windows) or "Cmd-S" (MacOS). Use them for all the exercise from now on!

## Source a script {-}
Source a script from the console instead of having to open it and source from RStudio is very useful when you want to save time and create re-usable pipelines or analysis. Sourcing a script means to execute all the line of codes in that script. It can be archieved by doing `source("path_to_file")`.
<br>
<br>
Now, head to the next chapter in which we will talk about numbers.